### ISSUE TITLE
iOSで星追加時にダブルタップで拡大してしまう

### ISSUE THREAD

**Issue by Compeito** [Compeito/tsukuriga#40]
https://twitter.com/i_k2254_ugo/status/1123112465129033730

これで解決できるらしい  http://neos21.hatenablog.com/entry/2018/12/22/080000
```css
html {
  touch-action: manipulation;
}
```
